Yarik sagotly fab
fenix1851/go-file-server pull request #16
Opened 2023-09-28 19:29 UTC by YaroslavNevsky

dont hate me if i make a shit please............

2023-09-28 21:15 UTC, sagotly commented
mostly sure have some bugs in it. Proper bug test needed

2023-10-02 11:40 UTC, fenix1851 requested changes

2023-10-02 11:40 UTC, fenix1851 commented on handlers/directory_handler.go
> +	//get uploaded files
what is this? @sagotly

2023-10-02 11:40 UTC, fenix1851 commented on handlers/directory_handler.go
> +		//clear cache
nice, this is actually good)

2023-10-02 11:40 UTC, fenix1851 commented on handlers/directory_handler.go
> +		fmt.Println("Ошибка разбора URL:", err)
return some responce, maybe 400

2023-10-02 11:40 UTC, fenix1851 commented on handlers/directory_handler.go
> +	fmt.Println("\nkonec________________________________")
what is this language?)

2023-10-02 11:40 UTC, fenix1851 commented on handlers/directory_handler.go
> +		fmt.Printf("error has accured:%s", err)
occurred

2023-10-02 11:40 UTC, fenix1851 commented on templates/directory.html
> -        /* Голубовато-синеватое свечение */
thx

2023-10-02 11:40 UTC, fenix1851 commented on templates/directory.html
> -            <span class="icon">📁</span> <!-- Значок папки -->
thx

2023-10-02 11:40 UTC, fenix1851 commented on templates/directory.html
> -            <span class="icon">📄</span> <!-- Значок файла -->
thx

2023-10-02 11:40 UTC, fenix1851 commented on templates/directory.html
> +        <a style="color: #d6e2e3; text-decoration: none; font-weight: bold;  font-family: 'Ubuntu', sans-serif;" href="https://github.com/fenix1851/go-file-server">GitHub Repository</a>
??? why all this styles are inside attribute?

2023-10-02 11:40 UTC, fenix1851 commented on templates/directory.html
> +        const mobileMediaQuery = window.matchMedia("(max-width: 768px)");
🔥🔥🔥🔥🔥

2023-10-02 11:42 UTC, fenix1851 commented on handlers/directory_handler.go
> +	//get uploaded files
check code below 76 line

2023-10-02 11:42 UTC, fenix1851 commented on handlers/directory_handler.go
> +		fmt.Println("Ошибка разбора URL:", err)
check code below 173 line

2023-10-02 12:32 UTC, sagotly commented on handlers/directory_handler.go
> +	fmt.Println("\nkonec________________________________")
xD

2023-10-04 00:11 UTC, fenix1851 commented on handlers/directory_handler.go
> +		// Convert a Windows-style path to a Unix-style path
good)

2023-10-04 00:19 UTC, fenix1851 approved these changes
it's ok)

2023-10-04 00:19 UTC, merged